// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketApp.Data;

#nullable disable

namespace StockMarket.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240514223032_AddSeedingDataForCommentModel")]
    partial class AddSeedingDataForCommentModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockMarketApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StockMarketApp.Models.AppUserStock", b =>
                {
                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StockId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("AppUserStocks");
                });

            modelBuilder.Entity("StockMarketApp.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Apple has consistently produced innovative products.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(8204),
                            StockId = 1,
                            Title = "Great company!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "AAPL's stock price has been steadily increasing.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(8988),
                            StockId = 1,
                            Title = "Rising stock price"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Excited about Apple's upcoming product launches.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(8997),
                            StockId = 1,
                            Title = "Future prospects"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Microsoft's cloud business is driving impressive growth.",
                            CreatedOn = new DateTime(2024, 5, 8, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9004),
                            StockId = 2,
                            Title = "Strong growth"
                        },
                        new
                        {
                            Id = 5,
                            Content = "MSFT remains one of the largest tech companies globally.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9011),
                            StockId = 2,
                            Title = "Tech giant"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Microsoft's products span from software to hardware, providing stability.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9028),
                            StockId = 2,
                            Title = "Diverse portfolio"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Amazon's e-commerce platform continues to dominate the market.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9035),
                            StockId = 3,
                            Title = "E-commerce dominance"
                        },
                        new
                        {
                            Id = 8,
                            Content = "AMZN's investments in technology and logistics drive innovation.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9043),
                            StockId = 3,
                            Title = "Innovative company"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Amazon Web Services (AWS) remains a key driver of growth.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9051),
                            StockId = 3,
                            Title = "Expanding cloud business"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Google's search engine continues to dominate the market.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9060),
                            StockId = 4,
                            Title = "Search engine dominance"
                        },
                        new
                        {
                            Id = 11,
                            Content = "GOOGL's moonshot projects demonstrate their commitment to innovation.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9068),
                            StockId = 4,
                            Title = "Innovative projects"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Google's advertising business remains a significant revenue driver.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9075),
                            StockId = 4,
                            Title = "Advertising revenue"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Facebook's social media platforms continue to attract billions of users.",
                            CreatedOn = new DateTime(2024, 5, 8, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9084),
                            StockId = 5,
                            Title = "Social media giant"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Meta Platforms' focus on the metaverse is generating significant interest.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9091),
                            StockId = 5,
                            Title = "Metaverse initiatives"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Concerns about data privacy continue to impact FB's reputation.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9098),
                            StockId = 5,
                            Title = "Data privacy concerns"
                        },
                        new
                        {
                            Id = 16,
                            Content = "Tesla's electric vehicles continue to lead the market.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9105),
                            StockId = 6,
                            Title = "Electric vehicle leader"
                        },
                        new
                        {
                            Id = 17,
                            Content = "TSLA's advancements in battery technology are impressive.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9112),
                            StockId = 6,
                            Title = "Innovative technology"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Tesla faces challenges in scaling production to meet demand.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9121),
                            StockId = 6,
                            Title = "Production challenges"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Warren Buffett's value investing approach remains influential.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9129),
                            StockId = 7,
                            Title = "Value investing"
                        },
                        new
                        {
                            Id = 20,
                            Content = "BRK-A's portfolio includes a wide range of businesses.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9136),
                            StockId = 7,
                            Title = "Diverse portfolio"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Berkshire Hathaway's long-term investment strategy is well-respected.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9143),
                            StockId = 7,
                            Title = "Investment strategy"
                        },
                        new
                        {
                            Id = 22,
                            Content = "NVIDIA's graphics technology remains at the forefront of the industry.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9150),
                            StockId = 8,
                            Title = "Graphics technology leader"
                        },
                        new
                        {
                            Id = 23,
                            Content = "NVDA's GPUs continue to dominate the gaming market.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9157),
                            StockId = 8,
                            Title = "Gaming market dominance"
                        },
                        new
                        {
                            Id = 24,
                            Content = "NVIDIA's AI and data center segments are driving significant growth.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9164),
                            StockId = 8,
                            Title = "AI and data center growth"
                        },
                        new
                        {
                            Id = 25,
                            Content = "JPM is one of the largest financial institutions globally.",
                            CreatedOn = new DateTime(2024, 5, 8, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9171),
                            StockId = 9,
                            Title = "Financial services leader"
                        },
                        new
                        {
                            Id = 26,
                            Content = "JPMorgan Chase's business model spans retail banking to investment banking.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9178),
                            StockId = 9,
                            Title = "Diversified business model"
                        },
                        new
                        {
                            Id = 27,
                            Content = "Regulatory scrutiny remains a challenge for JPM and other banks.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9186),
                            StockId = 9,
                            Title = "Regulatory challenges"
                        },
                        new
                        {
                            Id = 28,
                            Content = "Visa's payment network facilitates billions of transactions globally.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9193),
                            StockId = 10,
                            Title = "Global payments leader"
                        },
                        new
                        {
                            Id = 29,
                            Content = "V's investments in digital payments are driving growth.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9200),
                            StockId = 10,
                            Title = "Digital payments growth"
                        },
                        new
                        {
                            Id = 30,
                            Content = "Visa's partnerships with fintech companies strengthen its position.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9207),
                            StockId = 10,
                            Title = "Partnership strategies"
                        },
                        new
                        {
                            Id = 31,
                            Content = "Procter & Gamble's brands are household names worldwide.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9214),
                            StockId = 11,
                            Title = "Consumer goods giant"
                        },
                        new
                        {
                            Id = 32,
                            Content = "PG continues to innovate with new product offerings.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9221),
                            StockId = 11,
                            Title = "Product innovation"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Procter & Gamble operates in over 180 countries.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9228),
                            StockId = 11,
                            Title = "Global market presence"
                        },
                        new
                        {
                            Id = 34,
                            Content = "Disney's entertainment properties span movies, TV, and theme parks.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9238),
                            StockId = 12,
                            Title = "Entertainment powerhouse"
                        },
                        new
                        {
                            Id = 35,
                            Content = "DIS's streaming services continue to gain subscribers.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9245),
                            StockId = 12,
                            Title = "Streaming growth"
                        },
                        new
                        {
                            Id = 36,
                            Content = "Disney's theme parks are seeing a gradual recovery in attendance.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9252),
                            StockId = 12,
                            Title = "Theme park recovery"
                        },
                        new
                        {
                            Id = 37,
                            Content = "Home Depot is the largest home improvement retailer in the U.S.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9259),
                            StockId = 13,
                            Title = "Home improvement leader"
                        },
                        new
                        {
                            Id = 38,
                            Content = "HD benefits from the trend of consumers doing home improvement projects.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9266),
                            StockId = 13,
                            Title = "DIY trend"
                        },
                        new
                        {
                            Id = 39,
                            Content = "Home Depot's online sales continue to grow.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9273),
                            StockId = 13,
                            Title = "E-commerce growth"
                        },
                        new
                        {
                            Id = 40,
                            Content = "Comcast is one of the largest telecommunications companies in the U.S.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9280),
                            StockId = 14,
                            Title = "Telecommunications leader"
                        },
                        new
                        {
                            Id = 41,
                            Content = "CMCSA is expanding its broadband infrastructure.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9287),
                            StockId = 14,
                            Title = "Broadband expansion"
                        },
                        new
                        {
                            Id = 42,
                            Content = "Comcast's acquisitions in media strengthen its content portfolio.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9294),
                            StockId = 14,
                            Title = "Media acquisitions"
                        },
                        new
                        {
                            Id = 43,
                            Content = "UnitedHealth is one of the largest healthcare companies in the U.S.",
                            CreatedOn = new DateTime(2024, 5, 8, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9301),
                            StockId = 15,
                            Title = "Healthcare giant"
                        },
                        new
                        {
                            Id = 44,
                            Content = "UNH offers a wide range of healthcare services.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9309),
                            StockId = 15,
                            Title = "Healthcare services"
                        },
                        new
                        {
                            Id = 45,
                            Content = "UnitedHealth's insurance segment remains profitable.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9316),
                            StockId = 15,
                            Title = "Insurance segment"
                        },
                        new
                        {
                            Id = 46,
                            Content = "Alibaba is the largest e-commerce company in China.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9323),
                            StockId = 16,
                            Title = "E-commerce leader"
                        },
                        new
                        {
                            Id = 47,
                            Content = "BABA's cloud computing business continues to grow rapidly.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9330),
                            StockId = 16,
                            Title = "Cloud computing growth"
                        },
                        new
                        {
                            Id = 48,
                            Content = "Alibaba faces regulatory challenges in China.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9337),
                            StockId = 16,
                            Title = "Regulatory challenges"
                        },
                        new
                        {
                            Id = 49,
                            Content = "PayPal is a leading provider of digital payment solutions.",
                            CreatedOn = new DateTime(2024, 5, 10, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9344),
                            StockId = 17,
                            Title = "Digital payments leader"
                        },
                        new
                        {
                            Id = 50,
                            Content = "PYPL's mobile payment volume continues to grow.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9351),
                            StockId = 17,
                            Title = "Mobile payment growth"
                        },
                        new
                        {
                            Id = 51,
                            Content = "PayPal's partnerships with merchants drive adoption.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9358),
                            StockId = 17,
                            Title = "Partnership strategies"
                        },
                        new
                        {
                            Id = 52,
                            Content = "Netflix remains the dominant player in the streaming industry.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9366),
                            StockId = 18,
                            Title = "Streaming leader"
                        },
                        new
                        {
                            Id = 53,
                            Content = "NFLX invests heavily in original content production.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9373),
                            StockId = 18,
                            Title = "Content production"
                        },
                        new
                        {
                            Id = 54,
                            Content = "Netflix continues to add subscribers globally.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9380),
                            StockId = 18,
                            Title = "Subscriber growth"
                        },
                        new
                        {
                            Id = 55,
                            Content = "Salesforce is the leading provider of customer relationship management software.",
                            CreatedOn = new DateTime(2024, 5, 8, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9387),
                            StockId = 19,
                            Title = "CRM leader"
                        },
                        new
                        {
                            Id = 56,
                            Content = "CRM's cloud computing segment is driving revenue growth.",
                            CreatedOn = new DateTime(2024, 5, 11, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9474),
                            StockId = 19,
                            Title = "Cloud computing growth"
                        },
                        new
                        {
                            Id = 57,
                            Content = "Salesforce's acquisitions expand its product offerings.",
                            CreatedOn = new DateTime(2024, 5, 13, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9481),
                            StockId = 19,
                            Title = "Acquisition strategy"
                        },
                        new
                        {
                            Id = 58,
                            Content = "Intel is one of the largest semiconductor companies globally.",
                            CreatedOn = new DateTime(2024, 5, 9, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9488),
                            StockId = 20,
                            Title = "Semiconductor leader"
                        },
                        new
                        {
                            Id = 59,
                            Content = "INTC's processors power a wide range of computing devices.",
                            CreatedOn = new DateTime(2024, 5, 12, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9495),
                            StockId = 20,
                            Title = "Processor innovation"
                        },
                        new
                        {
                            Id = 60,
                            Content = "Intel faces competition from AMD and other players in the data center market.",
                            CreatedOn = new DateTime(2024, 5, 14, 1, 30, 31, 532, DateTimeKind.Local).AddTicks(9502),
                            StockId = 20,
                            Title = "Competition in data center market"
                        });
                });

            modelBuilder.Entity("StockMarketApp.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LatestProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketValue")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            Industry = "Technology",
                            LatestProfit = 10.2m,
                            MarketValue = 220000000000L,
                            Price = 145.67m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft Corporation",
                            Industry = "Technology",
                            LatestProfit = 15.8m,
                            MarketValue = 210000000000L,
                            Price = 278.05m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Amazon.com Inc.",
                            Industry = "Retail",
                            LatestProfit = 25.1m,
                            MarketValue = 1700000000000L,
                            Price = 3223.82m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Alphabet Inc.",
                            Industry = "Technology",
                            LatestProfit = 20.5m,
                            MarketValue = 1600000000000L,
                            Price = 2369.01m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Meta Platforms Inc.",
                            Industry = "Technology",
                            LatestProfit = 12.3m,
                            MarketValue = 900000000000L,
                            Price = 311.18m,
                            Symbol = "FB"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Tesla Inc.",
                            Industry = "Automotive",
                            LatestProfit = 6.4m,
                            MarketValue = 570000000000L,
                            Price = 589.74m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Berkshire Hathaway Inc.",
                            Industry = "Finance",
                            LatestProfit = 42.9m,
                            MarketValue = 600000000000L,
                            Price = 418715.00m,
                            Symbol = "BRK-A"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "NVIDIA Corporation",
                            Industry = "Technology",
                            LatestProfit = 8.7m,
                            MarketValue = 370000000000L,
                            Price = 606.25m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "JPMorgan Chase & Co.",
                            Industry = "Finance",
                            LatestProfit = 19.6m,
                            MarketValue = 470000000000L,
                            Price = 160.92m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Visa Inc.",
                            Industry = "Finance",
                            LatestProfit = 13.5m,
                            MarketValue = 450000000000L,
                            Price = 234.75m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Procter & Gamble Co.",
                            Industry = "Consumer Goods",
                            LatestProfit = 10.8m,
                            MarketValue = 350000000000L,
                            Price = 134.56m,
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "The Walt Disney Company",
                            Industry = "Entertainment",
                            LatestProfit = 9.7m,
                            MarketValue = 340000000000L,
                            Price = 174.78m,
                            Symbol = "DIS"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "The Home Depot Inc.",
                            Industry = "Retail",
                            LatestProfit = 14.2m,
                            MarketValue = 350000000000L,
                            Price = 322.47m,
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Comcast Corporation",
                            Industry = "Telecommunications",
                            LatestProfit = 8.1m,
                            MarketValue = 250000000000L,
                            Price = 55.63m,
                            Symbol = "CMCSA"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "UnitedHealth Group Incorporated",
                            Industry = "Healthcare",
                            LatestProfit = 15.3m,
                            MarketValue = 410000000000L,
                            Price = 399.51m,
                            Symbol = "UNH"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "Alibaba Group Holding Limited",
                            Industry = "Technology",
                            LatestProfit = 20.2m,
                            MarketValue = 600000000000L,
                            Price = 214.50m,
                            Symbol = "BABA"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "PayPal Holdings Inc.",
                            Industry = "Technology",
                            LatestProfit = 11.9m,
                            MarketValue = 300000000000L,
                            Price = 258.65m,
                            Symbol = "PYPL"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Netflix Inc.",
                            Industry = "Entertainment",
                            LatestProfit = 7.6m,
                            MarketValue = 220000000000L,
                            Price = 498.62m,
                            Symbol = "NFLX"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Salesforce.com Inc.",
                            Industry = "Technology",
                            LatestProfit = 8.9m,
                            MarketValue = 220000000000L,
                            Price = 224.38m,
                            Symbol = "CRM"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Intel Corporation",
                            Industry = "Technology",
                            LatestProfit = 6.5m,
                            MarketValue = 240000000000L,
                            Price = 58.95m,
                            Symbol = "INTC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockMarketApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockMarketApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarketApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockMarketApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMarketApp.Models.AppUserStock", b =>
                {
                    b.HasOne("StockMarketApp.Models.ApplicationUser", "AppUser")
                        .WithMany("AppUserStocks")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StockMarketApp.Models.Stock", "Stock")
                        .WithMany("AppUserStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockMarketApp.Models.Comment", b =>
                {
                    b.HasOne("StockMarketApp.Models.ApplicationUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("StockMarketApp.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockMarketApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("AppUserStocks");
                });

            modelBuilder.Entity("StockMarketApp.Models.Stock", b =>
                {
                    b.Navigation("AppUserStocks");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
